config/routes.rb
Rails.application.routes.draw do
  resources :shared_notes
  resources :notes
  devise_for :users

  root 'notes#index'

end

app/models/note.rb
class Note < ActiveRecord::Base
  belongs_to :user
  has_many :shared_notes, as: :shareable, dependent: :destroy
end

app/models/shared_note.rb
class SharedNote < ActiveRecord::Base
  belongs_to :user
  belongs_to :note
  belongs_to :shareable, polymorphic: true
  belongs_to :sharer, class_name: 'User'
  has_many :shared_notes, as: :shareable, dependent: :destroy
  PERMISSIONS = %w[read update_note owner].freeze
  enum permissions: PERMISSIONS
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
   has_many :notes, dependent: :destroy
   has_many :shared_notes, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :set_note, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /notes
  # GET /notes.json
  def index
    @notes = current_user.notes
    @notes_shared = current_user.shared_notes
  end

  # GET /notes/1
  # GET /notes/1.json
  def show
  end

  # GET /notes/new
  def new
    @note = Note.new
  end

  # GET /notes/1/edit
  def edit
  end

  # POST /notes
  # POST /notes.json
  def create
    @note = current_user.notes.new(note_params)

    respond_to do |format|
      if @note.save
        format.html { redirect_to @note, notice: 'Note was successfully created.' }
        format.json { render :show, status: :created, location: @note }
      else
        format.html { render :new }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notes/1
  # PATCH/PUT /notes/1.json
  def update
    respond_to do |format|
      if @note.update(note_params)
        format.html { redirect_to @note, notice: 'Note was successfully updated.' }
        format.json { render :show, status: :ok, location: @note }
      else
        format.html { render :edit }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notes/1
  # DELETE /notes/1.json
  def destroy
    @note.destroy
    respond_to do |format|
      format.html { redirect_to notes_url, notice: 'Note was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_note
      @note = Note.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def note_params
      params.require(:note).permit(:user_id, :body)
    end
end

app/controllers/shared_notes_controller.rb
class SharedNotesController < ApplicationController
  before_action :set_shared_note, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # GET /shared_notes
  # GET /shared_notes.json
  def index
    @shared_notes = SharedNote.all
  end

  # GET /shared_notes/1
  # GET /shared_notes/1.json
  def show
  end

  # GET /shared_notes/new
  def new
    @shared_note = SharedNote.new
  end

  # GET /shared_notes/1/edit
  def edit
  end

  # POST /shared_notes
  # POST /shared_notes.json
  def create
    @shared_note = SharedNote.new(shared_note_params.merge(sharer_id: current_user.id))

    respond_to do |format|
      if @shared_note.save
        format.html { redirect_to @shared_note, notice: 'Shared note was successfully created.' }
        format.json { render :show, status: :created, location: @shared_note }
      else
        format.html { render :new }
        format.json { render json: @shared_note.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shared_notes/1
  # PATCH/PUT /shared_notes/1.json
  def update
    respond_to do |format|
      if @shared_note.update(shared_note_params)
        format.html { redirect_to @shared_note, notice: 'Shared note was successfully updated.' }
        format.json { render :show, status: :ok, location: @shared_note }
      else
        format.html { render :edit }
        format.json { render json: @shared_note.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shared_notes/1
  # DELETE /shared_notes/1.json
  def destroy
    @shared_note.destroy
    respond_to do |format|
      format.html { redirect_to shared_notes_url, notice: 'Shared note was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shared_note
      @shared_note = SharedNote.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def shared_note_params
      params.require(:shared_note).permit(:user_id, :sharer, :permissions, :shareable_id, :shareable_type, :note_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/shared_notes_helper.rb
module SharedNotesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NoteKeeping</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/notes/_form.html.erb
<%= form_for(@note) do |f| %>
  <% if @note.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@note.errors.count, "error") %> prohibited this note from being saved:</h2>

      <ul>
      <% @note.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_field :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/notes/edit.html.erb
<h1>Editing Note</h1>

<%= render 'form' %>

<%= link_to 'Show', @note %> |
<%= link_to 'Back', notes_path %>

app/views/notes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Notes</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Body</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @notes.each do |note| %>
      <tr>
        <td><%= note.user.email %></td>
        <td><%= note.body %></td>
        <td><%= link_to 'Show', note %></td>
        <td><%= link_to 'Edit', edit_note_path(note) %></td>
        <td><%= link_to 'Destroy', note, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td>
          <%= form_for SharedNote.new do |f| %>
            <%= f.hidden_field :note_id, value: note.id%>
            <%= f.hidden_field :sharer_id, value: current_user.id %>
            <%= f.hidden_field :shareable_id, value: note.id %>
            <%= f.hidden_field :shareable_type, value: note.class %>
            <%= select("shared_note", "user_id", User.where.not(id: [current_user.id] + SharedNote.where(note_id: note.id).pluck(:user_id)).collect {|p| [ p.email, p.id ] }) %>
            <%= select("shared_note", "permissions", SharedNote::PERMISSIONS.each_with_index {|p, i| [ p, i ] }) %>
            <%= f.submit 'Share' %>
          <% end %>
        </td>
      </tr>
    <% end %>
    <% @notes_shared.each do |snote| %>
      <tr>
        <td><%= snote.sharer.email %></td>
        <td><%= snote.note.body %></td>
        <% if snote.read? %>
          <td><%= link_to 'Show', snote.note %></td>
        <% elsif snote.update_note? %>
          <td><%= link_to 'Show', snote.note %></td>
          <td><%= link_to 'Edit', edit_note_path(snote.note) %></td>
        <% else %>
          <td><%= link_to 'Show', snote.note %></td>
          <td><%= link_to 'Edit', edit_note_path(snote.note) %></td>
          <td><%= link_to 'Destroy', snote.note, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
        <td>
          <%= form_for SharedNote.new do |f| %>
            <%= f.hidden_field :note_id, value: snote.note_id%>
            <%= f.hidden_field :sharer_id, value: current_user.id %>
            <%= f.hidden_field :shareable_id, value: snote.id %>
            <%= f.hidden_field :shareable_type, value: snote.class %>
            <%= select("shared_note", "user_id", User.where.not(id: [current_user.id] + SharedNote.where(note_id: snote.note_id).pluck(:user_id)).collect {|p| [ p.email, p.id ] }) %>
            <% if snote.read? %>
              <%= select("shared_note", "permissions", [[ 'read', 0 ]]) %>
            <% elsif snote.update_note? %>
              <%= select("shared_note", "permissions", [[ 'read', 0 ], ['update_note', 1]]) %>
            <% else %>
              <%= select("shared_note", "permissions", SharedNote::PERMISSIONS.each_with_index {|p, i| [ p, i ] }) %>
            <% end %>
            <%= f.submit 'Share' %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Note', new_note_path %>

app/views/notes/new.html.erb
<h1>New Note</h1>

<%= render 'form' %>

<%= link_to 'Back', notes_path %>

app/views/notes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @note.user %>
</p>

<p>
  <strong>Body:</strong>
  <%= @note.body %>
</p>

<%= link_to 'Edit', edit_note_path(@note) %> |
<%= link_to 'Back', notes_path %>

app/views/shared_notes/_form.html.erb
<%= form_for(@shared_note) do |f| %>
  <% if @shared_note.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@shared_note.errors.count, "error") %> prohibited this shared_note from being saved:</h2>

      <ul>
      <% @shared_note.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :sharer %><br>
    <%= f.text_field :sharer %>
  </div>
  <div class="field">
    <%= f.label :permissions %><br>
    <%= f.number_field :permissions %>
  </div>
  <div class="field">
    <%= f.label :shareable_id %><br>
    <%= f.text_field :shareable_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/shared_notes/edit.html.erb
<h1>Editing Shared Note</h1>

<%= render 'form' %>

<%= link_to 'Show', @shared_note %> |
<%= link_to 'Back', shared_notes_path %>

app/views/shared_notes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Shared Notes</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Sharer</th>
      <th>Permissions</th>
      <th>Shareable</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @shared_notes.each do |shared_note| %>
      <tr>
        <td><%= shared_note.user %></td>
        <td><%= shared_note.sharer %></td>
        <td><%= shared_note.permissions %></td>
        <td><%= shared_note.shareable %></td>
        <td><%= link_to 'Show', shared_note %></td>
        <td><%= link_to 'Edit', edit_shared_note_path(shared_note) %></td>
        <td><%= link_to 'Destroy', shared_note, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Shared note', new_shared_note_path %>

app/views/shared_notes/new.html.erb
<h1>New Shared Note</h1>

<%= render 'form' %>

<%= link_to 'Back', shared_notes_path %>

app/views/shared_notes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @shared_note.user %>
</p>

<p>
  <strong>Sharer:</strong>
  <%= @shared_note.sharer %>
</p>

<p>
  <strong>Permissions:</strong>
  <%= @shared_note.permissions %>
</p>

<p>
  <strong>Shareable:</strong>
  <%= @shared_note.shareable %>
</p>

<%= link_to 'Edit', edit_shared_note_path(@shared_note) %> |
<%= link_to 'Back', shared_notes_path %>